"""initial schema

Revision ID: 946ed1fcdf86
Revises: 
Create Date: 2026-05-29 10:14:35.251863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '946ed1fcdf86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fundamentals',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('pe_ratio', sa.Numeric(), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(), nullable=True),
    sa.Column('ps_ratio', sa.Numeric(), nullable=True),
    sa.Column('ev_ebitda', sa.Numeric(), nullable=True),
    sa.Column('revenue', sa.Numeric(), nullable=True),
    sa.Column('net_income', sa.Numeric(), nullable=True),
    sa.Column('market_cap', sa.Numeric(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'report_date', 'source')
    )
    op.create_table('price_bars',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('adj_factor', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('quality_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'timestamp_utc', 'source')
    )
    # ### end Alembic commands ###

    # TimescaleDB: make price_bars a hypertable partitioned on time, and add the
    # (symbol, time DESC) index the mandatory query pattern relies on (data-contracts §6-7).
    op.execute("SELECT create_hypertable('price_bars', 'timestamp_utc')")
    op.create_index(
        "ix_price_bars_symbol_time",
        "price_bars",
        ["symbol", sa.text("timestamp_utc DESC")],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_price_bars_symbol_time", table_name="price_bars")
    op.drop_table('price_bars')
    op.drop_table('fundamentals')
    op.drop_table('data_quality_reports')
    # ### end Alembic commands ###
